// <auto-generated />
using System;
using ExTrack.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExTrack.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExTrack.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#007BFF");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#007BFF",
                            Description = "Groceries, restaurants, coffee",
                            Name = "Food & Dining"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#28A745",
                            Description = "Gas, ride-sharing, public transit",
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FFC107",
                            Description = "Electricity, water, internet, phone",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#DC3545",
                            Description = "Movies, concerts, subscriptions",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#6F42C1",
                            Description = "Clothes, household items, personal care",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#17A2B8",
                            Description = "Doctor visits, prescriptions, gym",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#E83E8C",
                            Description = "Rent, mortgage, home maintenance",
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#FD7E14",
                            Description = "Car, health, home insurance",
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#007BFF",
                            Description = "Courses, books, tuition",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#20C997",
                            Description = "Apps, software, memberships",
                            Name = "Subscriptions"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#0DCAF0",
                            Description = "Flights, hotels, vacation",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#6C757D",
                            Description = "Office supplies, professional development",
                            Name = "Work-Related"
                        },
                        new
                        {
                            Id = 13,
                            Color = "#198754",
                            Description = "Gifts for people, charity",
                            Name = "Gifts & Donations"
                        },
                        new
                        {
                            Id = 14,
                            Color = "#FF6B6B",
                            Description = "Loan payments, credit card payments",
                            Name = "Debt Payments"
                        },
                        new
                        {
                            Id = 15,
                            Color = "#495057",
                            Description = "Catch-all for things that don't fit",
                            Name = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("ExTrack.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExTrack.API.Models.Expense", b =>
                {
                    b.HasOne("ExTrack.API.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExTrack.API.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
